version: "3.8"

services:

  database:
    image: postgres:13-alpine
    container_name: gs-homework-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 3s
    #    volumes:
    #      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env