batch:
  size: 10000

default:
  page:
    size: 20

spring:

  config:
    import: 'optional:file:.env[.properties]'

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  logging:
    pattern:
      console: "%d [%t] %-5level %logger{36} - %msg%n"
      file: "%d [%t] %-5level %logger{36} - %msg%n"
    level:
      geo.steering.homework: DEBUG
    file:
      path: /logs
      name: ${logging.file.path}/log.log